// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrIeAKqdQR_obKsgW2KG4WjcMJj0UWmU',
    appId: '1:773504739164:web:6bb95ce35f74699eb50399',
    messagingSenderId: '773504739164',
    projectId: 'inventorymanagement-app-64fdc',
    authDomain: 'inventorymanagement-app-64fdc.firebaseapp.com',
    storageBucket: 'inventorymanagement-app-64fdc.firebasestorage.app',
    measurementId: 'G-L893NGN74L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr0WHnUcl-Le5YjmsduK03ApTNqm3UN7E',
    appId: '1:773504739164:android:cb7299e93257d99fb50399',
    messagingSenderId: '773504739164',
    projectId: 'inventorymanagement-app-64fdc',
    storageBucket: 'inventorymanagement-app-64fdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8kmn8CiAMM2uKAn6sEpfij5-Jy9WnN_M',
    appId: '1:773504739164:ios:14742f14aef59be4b50399',
    messagingSenderId: '773504739164',
    projectId: 'inventorymanagement-app-64fdc',
    storageBucket: 'inventorymanagement-app-64fdc.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8kmn8CiAMM2uKAn6sEpfij5-Jy9WnN_M',
    appId: '1:773504739164:ios:14742f14aef59be4b50399',
    messagingSenderId: '773504739164',
    projectId: 'inventorymanagement-app-64fdc',
    storageBucket: 'inventorymanagement-app-64fdc.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIrIeAKqdQR_obKsgW2KG4WjcMJj0UWmU',
    appId: '1:773504739164:web:d9e67366068a9471b50399',
    messagingSenderId: '773504739164',
    projectId: 'inventorymanagement-app-64fdc',
    authDomain: 'inventorymanagement-app-64fdc.firebaseapp.com',
    storageBucket: 'inventorymanagement-app-64fdc.firebasestorage.app',
    measurementId: 'G-LQSEYEXF3H',
  );
}
